[theme]
primaryColor = "#CBA35B"
backgroundColor = "#FAF9F7"
secondaryBackgroundColor = "#F8F4E6"
textColor = "#4E342E"

[server]
runOnSave = true
maxUploadSize = 2000

[client]
showSidebarNavigation = false

